server:
  port: 8080
  address: 0.0.0.0  # 监听所有网络接口

socketio:
  host: 0.0.0.0
  port: 9092

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${DB_URL:jdbc:mysql://localhost:3306/sat?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:}"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
      file-size-threshold: 0
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    username: ${MAIL_USERNAME:satbuddyteam@gmail.com}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    port: ${MAIL_PORT:587}
    sslEnable: ${MAIL_SSL_ENABLE:false}
    sender-name: SAT-Buddy
    default-encoding: UTF-8
    properties:
      mail:
        from: ${MAIL_USERNAME:satbuddyteam@gmail.com}
        debug: false
        smtp:
          auth: true
          connectiontimeout: 60000
          timeout: 120000
          writetimeout: 60000
          ssl:
            enable: ${MAIL_SSL_ENABLE:false}
          starttls:
            enable: true
            required: true

# 文件上传配置
file:
  upload:
    path: D:/uploads/
    max-size: 10485760  # 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sts.classSync.model

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:446311994602-2rtodkte7ldbp4f2qhnpusj8anf09vfg.apps.googleusercontent.com}
